# author: Exlau chen
version: "1.0.0"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter1"
    ports:
      - "9100:9100"
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus1"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/prometheus_data:/prometheus"
  grafana:
    image: grafana/grafana
    container_name: "grafana1"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./prometheus/grafana_data:/var/lib/grafana"
  mongo:
    image: mongo:4.0
    container_name: 'mongo1'
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_USERNAME: exlau # 暂时使用
      MONGO_PASSWORD: exlau # 暂时使用
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./prometheus/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  # frontend:
  #   build:
  #     context: ./prom_graph_fronend  # 前端应用的路径
  #     dockerfile: Dockerfile        # Dockerfile的文件名
  #   container_name: "frontend1"
  #   restart: always
  #   ports:
  #     - "3000:8080"
  # backend:
  #   build:
  #     context: ./backend  # 前端应用的路径
  #     dockerfile: Dockerfile        # Dockerfile的文件名
  #   container_name: "backend1"
  #   restart: always
  #   ports:
  #     - "4000:4000"   

volumes:
  mongo_data: